version: '3.7'

services:
  main:
    container_name: quml2xform
    image: samagragovernance/quml2xform:latest
    ports:
      - ${PORT}:3000
    env_file:
      - .env
    volumes:
    - gen:/app/gen

volumes:
  gen: